### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by koenpunt** [Tsunamii/IVTool#8]
I must say I'm not very familiar with Java, but I figured that building only 4 files shouldn't be that hard? Or do I need an additional build tool/configuration?

**Comment by Tsunamii** [comment]
just use the .jar file :) it's a prebuild version of the latest commit

**Comment by koenpunt** [comment]
Yeah I understand, but it has issues with my Java version, so I thought I could rebuild it myself using my version of Java

**Comment by Tsunamii** [comment]
won't be that easy since there are some files missing in the commit but this should work:
1) set up a new eclipse/netbeans project 
2) insert alle the files from the src folder
3) add apache commons cli to your build path
4) build the jar from the latest dev commit of the java api
5) add it to the build path
6) run it from eclipse/nebeans or create a jar with it

**Comment by koenpunt** [comment]
Thanks, will try that
